// Pure logic tests — no database required: node tests/unit.mjs
import assert from 'node:assert/strict';
import { healthScore, onboarding, slaState, agingBucket } from '../server/health.mjs';
import { redact } from '../server/audit.mjs';
import { permissionsFor, INTERNAL_ROLES, PERMISSIONS } from '../server/rbac.mjs';
const now = Date.parse('2026-09-28T12:00:00Z');
const healthy = { clinic_name: 'C', city: 'Paris', address: 'a', identifier: 'x', phone: '1', team_count: 3, agenda_configured: true, patient_count: 10, quote_count: 4, training_done_at: '2026-09-01', activity_14d: 40, activity_prev_14d: 38, overdue_count: 0, tickets_14d: 0, critical_open: 0, last_activity_at: '2026-09-28T09:00:00Z' };
let h = healthScore(healthy, now);
assert.equal(h.score, 100); assert.equal(h.status, 'stable'); assert.equal(h.dimensions.length, 5); assert.equal(h.reasons.length, 5);
h = healthScore({ ...healthy, activity_14d: 20, activity_prev_14d: 40, tickets_14d: 3, overdue_count: 4, overdue_max_days: 70, last_activity_at: '2026-09-10T00:00:00Z' }, now);
assert.equal(h.score, 20 + 12 + 5 + 6 + 4); assert.equal(h.status, 'risk');
assert(h.reasons.some((r) => r.includes('baisse de 50 %')));
assert.equal(healthScore({ ...healthy, critical_open: 1, tickets_14d: 1 }, now).dimensions.find((d) => d.key === 'support').score, 4);
assert.equal(healthScore({}, now).score, Math.round(20 / 7) + 0 + 20 + 20 + 0);
const ob = onboarding({ clinic_name: 'C', city: 'P', address: 'a', identifier: 'x', phone: '1', team_count: 0, pending_invites: 1 });
assert.equal(ob.completed, 3); assert.equal(ob.total, 7); assert.equal(ob.percent, 43);
assert.equal(slaState({ priority: 'critical', status: 'new', created_at: '2026-09-28T07:00:00Z' }, now).state, 'breached');
assert.equal(slaState({ priority: 'normal', status: 'new', created_at: '2026-09-28T07:00:00Z' }, now).state, 'ok');
assert.equal(slaState({ priority: 'normal', status: 'resolved', created_at: '2026-09-01T07:00:00Z' }, now).state, 'done');
assert.deepEqual([0, 30, 31, 60, 61, 90, 91].map(agingBucket), ['0-30', '0-30', '31-60', '31-60', '61-90', '61-90', '90+']);
const r = redact({ name: 'x', password_hash: 'h', token: 't', nested: { recovery_hash: 'r', ok: 1, allergies: 'a' }, file: 'data:image/png;base64,AAA' });
assert.deepEqual(r, { name: 'x', nested: { ok: 1 }, file: '[fichier]' });
assert.equal(permissionsFor('platform_owner').size, PERMISSIONS.length);
assert(!permissionsFor('support_agent').has('billing.read'));
assert(!permissionsFor('read_only_analyst').has('account.suspend'));
assert(permissionsFor('unknown').has('rbac.manage'), 'unknown roles fall back to owner only when no row exists');
for (const role of Object.values(INTERNAL_ROLES)) for (const p of role.permissions) assert(PERMISSIONS.includes(p), p);
import { readFileSync } from 'node:fs';
import { MIGRATIONS } from '../server/migrations.mjs';
for (const m of MIGRATIONS) assert.equal(m.sql, readFileSync(new URL(`../scripts/migrations/${m.id}.sql`, import.meta.url), 'utf8'), 'embedded migration in sync: ' + m.id);
console.log('PASS: health score, onboarding, SLA, aging, audit redaction, RBAC matrix, embedded migrations in sync.');
