import {useEffect,useState} from 'react';
import {api,money} from './client';
type Client={id:string;name:string;email:string;address:string;company_id:string;monthly_amount:number;service_label:string;subscription_status:string;stripe_session_id?:string;stripe_subscription_id?:string};
const labels:Record<string,string>={not_started:'Non activé',awaiting_mandate:'Mandat à signer',active:'Actif',trialing:'Période d’essai',past_due:'Paiement en retard',canceled:'Annulé',unpaid:'Impayé',incomplete:'Confirmation en cours',incomplete_expired:'Activation expirée'};
export default function BillingClients({readOnly=false}:{readOnly?:boolean}){
 const [clients,setClients]=useState<Client[]>([]),[invoices,setInvoices]=useState<any[]>([]),[editing,setEditing]=useState<Partial<Client>|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[canActivate,setCanActivate]=useState(false),[link,setLink]=useState('');
 const load=async()=>{try{const d=await api('billing-clients');setClients(d.clients);setInvoices(d.invoices);setReady(d.ready);setCanActivate(d.canActivate)}catch(e){setError((e as Error).message)}};useEffect(()=>{void load()},[]);
 return <section className="glass panel billing-clients"><div className="section-title"><div><h2>Clients & facturation mensuelle</h2><p>Les coordonnées de facturation de vos cabinets et clients, enregistrées une seule fois.</p></div><button disabled={readOnly} className="primary" onClick={()=>{setEditing({});setError('');setLink('')}}>Ajouter un client</button></div>
 {!ready&&<p className="billing-setup">Configuration Stripe SEPA en attente. Vous pouvez déjà enregistrer vos clients. Les prélèvements et l’envoi mensuel seront disponibles après connexion de Stripe et du service d’e-mail.</p>}
 {error&&<p className="form-error" role="alert">{error}</p>}
 {editing&&<form className="billing-client-form" onSubmit={async e=>{e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await api('billing-client-save',{id:editing.id,...Object.fromEntries(f)});setEditing(null);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><h3>{editing.id?'Modifier le client':'Nouveau client'}</h3><div className="form-grid"><label>Cabinet / raison sociale<input name="name" defaultValue={editing.name} required/></label><label>E-mail de facturation<input type="email" name="email" defaultValue={editing.email} required/></label><label>Adresse de facturation<input name="address" defaultValue={editing.address}/></label><label>SIRET<input name="company_id" defaultValue={editing.company_id}/></label><label>Prestation mensuelle<input name="service_label" defaultValue={editing.service_label||'Accompagnement SmilePec'} required/></label><label>Montant mensuel TTC (€)<input name="monthly_amount" type="number" min="0" max="100000" step="0.01" defaultValue={(editing.monthly_amount||0)/100} required/></label></div><p>Le client signera son mandat sur la page sécurisée Stripe. Aucune donnée bancaire n’est saisie dans SmilePec.</p><button className="primary" disabled={busy}>Enregistrer le client</button><button type="button" className="secondary" onClick={()=>setEditing(null)}>Annuler</button></form>}
 {link&&<div className="billing-mandate" role="status"><strong>Lien de signature du mandat</strong><p>À transmettre au client pour qu’il consulte le montant mensuel et autorise le prélèvement.</p><a href={link} target="_blank" rel="noreferrer">Ouvrir la page sécurisée Stripe</a><input readOnly value={link} aria-label="Lien du mandat SEPA"/></div>}
 <div className="billing-client-list">{clients.map(c=><article key={c.id}><div><h3>{c.name}</h3><p>{c.email}</p><small>{c.service_label} · {money(c.monthly_amount/100)} / mois</small></div><span className="badge">{labels[c.subscription_status]||c.subscription_status}</span><button className="secondary" disabled={readOnly||!!c.stripe_session_id||!!c.stripe_subscription_id} onClick={()=>setEditing(c)}>Modifier</button>{canActivate&&!readOnly&&<button className="secondary" disabled={!ready||busy||!!c.stripe_subscription_id||!c.monthly_amount} onClick={async()=>{setBusy(true);setError('');try{const d=await api('billing-checkout',{id:c.id});setLink(d.url);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Préparer le mandat SEPA</button>}</article>)}</div>
 {!clients.length&&!editing&&<p>Aucun client enregistré. Ajoutez votre premier cabinet et son e-mail de facturation.</p>}
 {!!invoices.length&&<><h3>Factures mensuelles</h3><div className="billing-client-list">{invoices.map(i=><article key={i.stripe_invoice_id}><div><strong>{i.number} · {i.client_name}</strong><p>{money(i.amount_due/100)} · {i.status==='paid'?'Payée':i.status==='open'?'Paiement en cours':i.status} · {i.email_sent_at?'E-mail envoyé':'Envoi en attente'}</p></div>{i.pdf_url&&<a className="secondary" href={i.pdf_url} target="_blank" rel="noreferrer">Facture PDF</a>}</article>)}</div></>}
 </section>
}
