import {useEffect,useRef,useState} from 'react';
import {api,Mission} from './client';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
type Live={id:string;title:string;sharing:boolean;latitude:number|null;longitude:number|null;assignee:string;photo_data:string;updated_at:string};
export default function LiveTracking({missions=[],patient=false}:{missions?:Mission[];patient?:boolean}){
 const [live,setLive]=useState<Live[]>([]),[sharing,setSharing]=useState(''),[error,setError]=useState(''),[pending,setPending]=useState(false);
 const host=useRef<HTMLDivElement>(null),map=useRef<L.Map|null>(null),markers=useRef<L.LayerGroup|null>(null),active=useRef(''),timer=useRef<ReturnType<typeof setInterval>|undefined>(undefined),inFlight=useRef(false);
 const refresh=()=>api('mission-live').then(d=>setLive(d.missions)).catch(e=>setError(e.message));
 const stop=async()=>{const id=active.current;active.current='';clearInterval(timer.current);setSharing('');if(id)try{await api('mission-location',{id,sharing:false});await refresh()}catch{setError('Arrêt local effectué. La position expire automatiquement sous une minute.')}};
 useEffect(()=>{refresh();const poll=setInterval(refresh,15000);const hide=()=>{if(document.hidden)void stop()};document.addEventListener('visibilitychange',hide);return()=>{clearInterval(poll);clearInterval(timer.current);document.removeEventListener('visibilitychange',hide);const id=active.current;active.current='';if(id)void api('mission-location',{id,sharing:false}).catch(()=>{})}},[]);
 useEffect(()=>{if(!host.current)return;const m=L.map(host.current,{scrollWheelZoom:false}).setView([46.6,2.2],5);map.current=m;L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap',maxZoom:19}).addTo(m);markers.current=L.layerGroup().addTo(m);const observer=new ResizeObserver(()=>m.invalidateSize());observer.observe(host.current);return()=>{observer.disconnect();m.remove();map.current=null}},[]);
 useEffect(()=>{markers.current?.clearLayers();const points:L.LatLngExpression[]=[];live.filter(m=>m.sharing&&m.latitude!==null&&m.longitude!==null).forEach(m=>{const el=document.createElement('div');el.className='gps-avatar';if(/^data:image\/(png|jpeg|webp);base64,/.test(m.photo_data||'')){const img=document.createElement('img');img.src=m.photo_data;img.alt=m.assignee;el.append(img)}else el.textContent=(m.assignee||'Pro').slice(0,2);const pos:L.LatLngExpression=[Number(m.latitude),Number(m.longitude)];points.push(pos);const label=document.createElement('span');label.textContent=m.assignee+' · '+m.title;L.marker(pos,{icon:L.divIcon({html:el,className:'gps-marker',iconSize:[44,44]})}).bindPopup(label).addTo(markers.current!)});if(points.length)map.current?.fitBounds(L.latLngBounds(points),{maxZoom:15,padding:[35,35]})},[live]);
 const start=(id:string)=>{if(!navigator.geolocation){setError('La géolocalisation est indisponible sur cet appareil.');return}setError('');setPending(true);active.current=id;const locate=()=>{if(inFlight.current||active.current!==id)return;inFlight.current=true;navigator.geolocation.getCurrentPosition(async p=>{try{if(active.current!==id)return;await api('mission-location',{id,sharing:true,latitude:p.coords.latitude,longitude:p.coords.longitude});if(active.current!==id){await api('mission-location',{id,sharing:false});return}setSharing(id);await refresh()}catch(e){setError((e as Error).message);await stop()}finally{setPending(false);inFlight.current=false}},()=>{inFlight.current=false;setPending(false);setError('Position non partagée : autorisation refusée ou signal indisponible.');void stop()},{enableHighAccuracy:true,timeout:10000,maximumAge:10000})};locate();timer.current=setInterval(locate,15000)};
 return <section className="glass panel live-tracking"><h2>{patient?'Arrivée de votre praticien':'Ma position · partage volontaire'}</h2><p>{patient?'Une position apparaît uniquement si le praticien choisit de la partager pendant votre rendez-vous.':'Vous partagez uniquement votre propre position pour la course choisie. Visible par le cabinet autorisé et le patient du rendez-vous. Le partage s’arrête en quittant cet écran ou en masquant l’application.'}</p>{error&&<p className="form-error" role="alert">{error}</p>}<div className="live-map" ref={host}/>{!live.some(m=>m.sharing)&&<p className="empty">Aucune position partagée actuellement.</p>}{!patient&&<div className="sharing-actions">{sharing||pending?<button className="secondary" onClick={()=>void stop()}>Arrêter le partage de ma position</button>:<><label>Course<select id="share-mission" defaultValue=""><option value="" disabled>Choisir une course</option>{missions.filter(m=>m.status!=='completed').map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label><button className="primary" onClick={()=>{const id=(document.getElementById('share-mission') as HTMLSelectElement)?.value;if(id)start(id);else setError('Choisissez une course avant de partager.')}}>Partager ma position</button></>}<small>{sharing?'Partage actif · mise à jour toutes les 15 secondes':pending?'Autorisation et localisation en cours…':'Partage désactivé par défaut · aucune collecte sans votre action'}</small></div>}</section>
}
