import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight} from 'lucide-react';
import {WorkTask,PatientRecord,Account,Dashboard,money} from './client';
import {PEC_STAGES,normalizeStage,PEC_GUIDANCE} from './pec';

export function PecBoard({tasks,edit,move}:{tasks:WorkTask[];edit:(task:WorkTask)=>void;move:(id:string,stage:string)=>Promise<boolean>}){
 const [dragged,setDragged]=useState(''),[target,setTarget]=useState(''),[busy,setBusy]=useState(false);
 const board=useRef<HTMLDivElement>(null);
 const [edges,setEdges]=useState({left:true,right:false});
 const updateEdges=()=>{const el=board.current;if(el)setEdges({left:el.scrollLeft<=2,right:el.scrollLeft+el.clientWidth>=el.scrollWidth-2})};
 useEffect(()=>{const el=board.current;if(!el)return;const observer=new ResizeObserver(updateEdges);observer.observe(el);updateEdges();return()=>observer.disconnect()},[]);
 const slide=(direction:number)=>{const el=board.current;if(!el)return;const column=el.querySelector<HTMLElement>('.pec-column');el.scrollBy({left:direction*((column?.offsetWidth||290)+18),behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})};
 const change=async(id:string,stage:string)=>{if(busy)return;setBusy(true);try{await move(id,stage)}finally{setBusy(false);setDragged('');setTarget('')}};
 return <div className="pec-board-shell"><details className="pec-guide"><summary>Comprendre les étapes du suivi PEC</summary><p>Chaque fiche ou sous-fiche représente un plan distinct. Son statut se modifie dans la fiche, dans la liste « Déplacer vers » ou par glisser-déposer.</p><ol>{PEC_STAGES.map(stage=><li key={stage}><strong>{stage}</strong><span>{PEC_GUIDANCE[stage]}</span></li>)}</ol></details><nav className="pec-board-navigation" aria-label="Navigation des colonnes PEC"><span>Parcourir les 9 colonnes</span><button type="button" className="secondary" aria-label="Colonnes précédentes" disabled={edges.left} onClick={()=>slide(-1)}><ArrowLeft size={20}/>À gauche</button><button type="button" className="secondary" aria-label="Colonnes suivantes" disabled={edges.right} onClick={()=>slide(1)}>À droite<ArrowRight size={20}/></button></nav><div ref={board} onScroll={updateEdges} tabIndex={0} role="region" onKeyDown={e=>{if(e.target!==e.currentTarget)return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();slide(e.key==='ArrowRight'?1:-1)}if(e.key==='Home'||e.key==='End'){e.preventDefault();board.current?.scrollTo({left:e.key==='Home'?0:board.current.scrollWidth,behavior:'instant'})}}} className="pec-board" aria-label="Suivi des dossiers PEC" aria-busy={busy}>{PEC_STAGES.map((stage,index)=><section key={stage} className={`pec-column tone-${index} ${target===stage?'drop-target':''}`} onDragOver={e=>{e.preventDefault();setTarget(stage)}} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain');if(tasks.some(t=>t.id===id))void change(id,stage)}}>
  <header><h2>{stage}</h2><span>{tasks.filter(t=>normalizeStage(t.stage)===stage).length}</span></header>
  <div className="pec-column-cards">{tasks.filter(t=>normalizeStage(t.stage)===stage).map(t=><article className="pec-card" key={t.id} draggable={!busy} onDragStart={e=>{e.dataTransfer.setData('text/plain',t.id);setDragged(t.id)}} onDragEnd={()=>{setDragged('');setTarget('')}} style={{opacity:dragged===t.id?.toString()?0.5:1}}>
   <button type="button" className="pec-card-open" onClick={()=>edit(t)}><h3>{t.title}</h3>{t.plan_name&&<span>{t.plan_name}</span>}{t.parent_task_id&&<small className="pec-subplan">Sous-fiche · plan de traitement</small>}<p>{t.description||'Aucun commentaire'}</p></button>
   <div className="pec-dates">{t.impression_date&&<span>Taille / empreinte · {new Date(t.impression_date).toLocaleDateString('fr-FR')}</span>}{t.placement_date&&<span>Pose · {new Date(t.placement_date).toLocaleDateString('fr-FR')}</span>}</div>
   <small>{t.assignee||'Responsable à attribuer'}</small>
   <label className="pec-status-label">Déplacer vers<select aria-label={`Statut de ${t.title}`} value={normalizeStage(t.stage)} disabled={busy} onChange={e=>void change(t.id,e.target.value)}>{PEC_STAGES.map(s=><option key={s}>{s}</option>)}</select></label>
  </article>)}{!tasks.some(t=>normalizeStage(t.stage)===stage)&&<p className="pec-empty">Déposez une fiche ici</p>}</div>
 </section>)}</div></div>
}

export function PecForm({task,patients,account,members,ownerId,ownerName,save,close,addPlan,openPlan,related,canBill}:{task:Partial<WorkTask>;patients:PatientRecord[];account:Account;members:Dashboard['members'];ownerId:string;ownerName:string;save:(body:any)=>Promise<boolean>;close:()=>void;addPlan:()=>void;openPlan:(task:WorkTask)=>void;related:WorkTask[];canBill:boolean}){
 const [selectedStage,setSelectedStage]=useState(normalizeStage(task.stage));
 const [tab,setTab]=useState("dossier"),[initial,setInitial]=useState(Number(task.initial_quote||0)),[final,setFinal]=useState(Number(task.final_quote||0)),[recovered,setRecovered]=useState(Number(task.recovered_amount||0));
 const [attachments,setAttachments]=useState(task.attachments||[]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const upload=async(kind:string,file?:File)=>{if(!file)return;setError('');if(!['application/pdf','image/png','image/jpeg','image/webp'].includes(file.type)||file.size>1200000){setError('Choisissez un PDF ou une image de moins de 1,2 Mo par document.');return}try{const url=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(new Error('Lecture du document impossible.'));r.readAsDataURL(file)});setAttachments(a=>[...a.filter(x=>x.kind!==kind),{kind,name:file.name,url}])}catch(e){setError((e as Error).message)}};
 const complete=['devis','mutuelle'].every(kind=>attachments.some(a=>a.kind===kind&&a.url));
 return <form onSubmit={async e=>{e.preventDefault();if(!complete||busy)return;const f=new FormData(e.currentTarget);setBusy(true);setError('');try{const requestedStage=(e.nativeEvent as SubmitEvent).submitter?.getAttribute("data-stage");const ok=await save({id:task.id,parent_task_id:task.parent_task_id,...Object.fromEntries(f),...(requestedStage?{stage:requestedStage}:{}),attachments:attachments.filter(a=>['devis','mutuelle'].includes(a.kind||''))});if(!ok)setError('La fiche n’a pas été enregistrée. Vérifiez les informations et réessayez.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>
 {error&&<p className="form-error" role="alert">{error}</p>}
 <label>Nom du patient / titre de la fiche<input name="title" defaultValue={task.title} required maxLength={200}/></label>
 <label>Plan de traitement<input name="plan_name" defaultValue={task.plan_name} placeholder="Ex. couronne secteur 1, implant secteur 3…" maxLength={180}/></label>
 <div className="pec-tabs" role="tablist" aria-label="Contenu de la fiche"><button type="button" role="tab" aria-selected={tab==='dossier'} onClick={()=>setTab('dossier')}>Dossier & documents</button>{canBill&&<button type="button" role="tab" aria-selected={tab==='finance'} onClick={()=>setTab('finance')}>Informations financières</button>}</div>
 <div hidden={tab!=='dossier'} className="pec-dossier-tab">
 <aside className="pec-step-help"><strong>{selectedStage}</strong><p>{PEC_GUIDANCE[selectedStage]}</p></aside>
 <div className="form-grid"><label>Statut<select name="stage" value={selectedStage} onChange={e=>setSelectedStage(e.target.value)}>{PEC_STAGES.map(s=><option key={s}>{s}</option>)}</select></label>

 <label>Responsable du cabinet<select name="assignee_id" defaultValue={task.assignee_id||''}><option value="">À attribuer</option><option value={ownerId}>{ownerName}</option>{members.filter(m=>m.active&&m.member_id!==ownerId).map(m=><option value={m.member_id} key={m.member_id}>{m.name} · {m.job_title}</option>)}</select></label>
 <label>Date de taille / empreinte<input name="impression_date" type="date" defaultValue={task.impression_date?.slice(0,10)}/></label>
 <label>Date de pose<input name="placement_date" type="date" defaultValue={task.placement_date?.slice(0,10)}/></label></div>
 <label>Commentaire<textarea name="description" rows={4} defaultValue={task.description} placeholder="Informations utiles, échanges et suivi du dossier…"/></label>
 {!!task.checklist?.length&&<details><summary>Anciennes notes de suivi</summary>{task.checklist.map(c=><p key={c.id}>{c.text}</p>)}</details>}
 <div className="pec-documents">{[['devis','Devis'],['mutuelle','Mutuelle']].map(([kind,label])=>{const document=attachments.find(a=>a.kind===kind);return <label key={kind}><strong>{label} nominatif * · {document ? "Ajouté" : "À ajouter"}</strong><span>Document au nom du patient · PDF ou image · 1,2 Mo maximum</span><input type="file" accept="application/pdf,image/png,image/jpeg,image/webp" onChange={e=>void upload(kind,e.target.files?.[0])}/>{document&&<a href={document.url} download={document.name}>{document.name} — Télécharger</a>}</label>})}</div>
 </div>
 {canBill&&<div hidden={tab!=='finance'} className="pec-financial-tab"><div className="form-grid"><label>Devis initial (€)<input name="initial_quote" type="number" min="0" max="100000000" step="0.01" value={initial} onChange={e=>setInitial(Number(e.target.value))}/></label><label>Devis définitif (€)<input name="final_quote" type="number" min="0" max="100000000" step="0.01" value={final} onChange={e=>setFinal(Number(e.target.value))}/></label><label>Montant récupéré (€)<input name="recovered_amount" type="number" min="0" max="100000000" step="0.01" value={recovered} onChange={e=>setRecovered(Number(e.target.value))}/></label><label>Date de rattachement au bilan<input name="financial_date" type="date" defaultValue={task.financial_date?.slice(0,10)||new Date().toISOString().slice(0,10)}/></label><label>Praticien<select name="practitioner_id" defaultValue={task.practitioner_id||ownerId}><option value={ownerId}>{ownerName}</option>{members.filter(m=>m.active&&m.role==='professional'&&m.member_id!==ownerId).map(m=><option value={m.member_id} key={m.member_id}>{m.name}</option>)}</select></label></div><div className="pec-difference"><span>Différence : devis définitif − devis initial</span><strong>{money(Math.round((final-initial)*100)/100)}</strong></div><p>Le montant récupéré est suivi séparément. Chaque plan est compté une seule fois, dans le mois de rattachement choisi.</p></div>}
 {!!task.id&&<section className="pec-related"><h3>Plans de traitement de ce patient</h3>{related.map(plan=><button className="secondary" type="button" key={plan.id} onClick={()=>openPlan(plan)}>{plan.plan_name||plan.title} · {normalizeStage(plan.stage)}</button>)}<button className="secondary" type="button" onClick={addPlan}>+ Créer une sous-fiche / un autre plan</button><small>Enregistrez vos modifications avant d’ouvrir un autre plan.</small></section>}
 {!complete&&<p className="form-error">Ajoutez le devis et la mutuelle pour pouvoir enregistrer la fiche.</p>}
 <div className="pec-form-actions"><button className="primary" disabled={!complete||busy}>{busy?'Enregistrement…':'Enregistrer la fiche'}</button>{selectedStage==='ACCORD PEC'&&<button className="primary" type="submit" data-stage="PEC À FACTURER" disabled={!complete||busy}>Facturer</button>}<button className="secondary" type="button" onClick={close} disabled={busy}>Annuler</button></div>
 {selectedStage==='ACCORD PEC'&&<p>« Facturer » enregistre la fiche et la déplace vers « PEC À FACTURER ». « Annuler » ferme sans modifier la colonne.</p>}
 </form>
}
