import {useEffect,useState} from 'react';
import {api,money,WorkTask} from './client';
type Row={month:string;practitioner_id:string|null;practitioner:string;plans:number;initial:string;final:string;difference:string;recovered:string};
export default function PecReport({revision,endpoint="pec-report"}:{revision:WorkTask[];endpoint?:string}){
 const [year,setYear]=useState(new Date().getFullYear()),[month,setMonth]=useState(''),[practitioner,setPractitioner]=useState(''),[rows,setRows]=useState<Row[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;setBusy(true);setError('');api(endpoint+'&year='+year).then(d=>{if(active)setRows(d.rows)}).catch(e=>{if(active){setRows([]);setError(e.message)}}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[year,revision,endpoint]);
 const filtered=rows.filter(r=>(!month||r.month===year+'-'+month)&&(!practitioner||(r.practitioner_id||'none')===practitioner));
 const sum=(key:'initial'|'final'|'difference'|'recovered')=>filtered.reduce((v,r)=>v+Math.round(Number(r[key])*100),0)/100;
 const practitioners=[...new Map(rows.map(r=>[r.practitioner_id||'none',r.practitioner])).entries()];
 const exportReport=()=>{const values=[['Mois','Praticien','Plans','Devis initiaux','Devis définitifs','Différence','Montant récupéré'],...filtered.map(r=>[r.month,r.practitioner,r.plans,r.initial,r.final,r.difference,r.recovered])];const csv='\uFEFF'+values.map(row=>row.map(v=>'"'+String(v).replace(/^([=+@-])/,String.fromCharCode(39)+'$1').replace(/"/g,'""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='bilan-pec-'+year+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 return <details className="pec-report glass panel"><summary>Bilan financier des plans de traitement</summary><p>Totaux du cabinet sélectionné, selon la date de rattachement de chaque plan.</p><div className="pec-report-filters"><label>Année<input type="number" min="2000" max="2100" value={year} onChange={e=>{const n=Number(e.target.value);if(n>=2000&&n<=2100)setYear(n)}}/></label><label>Mois<select value={month} onChange={e=>setMonth(e.target.value)}><option value="">Toute l’année</option>{Array.from({length:12},(_,i)=><option key={i} value={String(i+1).padStart(2,'0')}>{new Date(2026,i,1).toLocaleDateString('fr-FR',{month:'long'})}</option>)}</select></label><label>Praticien<select value={practitioner} onChange={e=>setPractitioner(e.target.value)}><option value="">Tous les praticiens</option>{practitioners.map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label><button className="secondary" disabled={busy||!filtered.length} onClick={exportReport}>Exporter le bilan</button></div>
 {error&&<p role="alert" className="form-error">{error}</p>}{busy?<p role="status">Calcul du bilan…</p>:<><div className="pec-report-totals">{([['Devis initiaux','initial'],['Devis définitifs','final'],['Différence cumulée','difference'],['Montant récupéré','recovered']] as const).map(([label,key])=><div key={key}><span>{label}</span><strong>{money(sum(key))}</strong></div>)}</div><div className="pec-report-table"><table><thead><tr><th>Mois</th><th>Praticien</th><th>Plans</th><th>Différence</th><th>Récupéré</th></tr></thead><tbody>{filtered.map(r=><tr key={r.month+(r.practitioner_id||'none')}><td>{r.month}</td><td>{r.practitioner}</td><td>{r.plans}</td><td>{money(Number(r.difference))}</td><td>{money(Number(r.recovered))}</td></tr>)}</tbody></table>{!filtered.length&&<p>Aucun montant enregistré pour cette période.</p>}</div></>}
 </details>
}
