import {useEffect,useState} from 'react';
import {api} from './client';
const rights=[['agenda','Agenda'],['patients_admin','Administratif patients'],['clinical','Dossier clinique'],['billing','Devis et factures'],['messages','Messagerie'],['tasks','Tâches et courses']];
const presets:Record<string,string[]>={'Dentiste associé':rights.map(x=>x[0]),'Assistant médical':['agenda','patients_admin','tasks'],'Secrétaire':['agenda','patients_admin','messages'],'Gestionnaire tiers payant':['patients_admin','billing','messages','tasks']};
type Member={id:string;name:string;email:string;job_title:string;permissions:string[];active:boolean;accepted:boolean;clinic_name?:string};
export default function TeamPanel(){
 const [members,setMembers]=useState<Member[]>([]),[invitations,setInvitations]=useState<Member[]>([]),[owner,setOwner]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<Member|null>(null),[role,setRole]=useState('Assistant médical'),[permissions,setPermissions]=useState(presets['Assistant médical']);
 const load=async()=>{try{const d=await api('team');setMembers(d.members);setInvitations(d.invitations);setOwner(d.owner)}catch(e){setError((e as Error).message)}};
 useEffect(()=>{load()},[]);
 const run=async(action:string,body:unknown)=>{setBusy(true);setError('');try{await api(action,body);setMessage(action==='clinic-member-add'?'Invitation disponible dans l’espace Équipe du destinataire.':'Accès mis à jour.');setEditing(null);await load();if(action==='team-accept')location.reload()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <section className="glass panel team-panel"><div className="section-title"><div><h2>Cabinet · Équipe & accès</h2><p>Invitez un compte existant, attribuez ses droits puis ajustez-les à tout moment.</p></div></div>{error&&<p role="alert" className="form-error">{error}</p>}{message&&<p role="status" className="save-notice">{message}</p>}
 {invitations.map(m=><article className="team-invitation" key={m.id}><strong>{m.clinic_name||m.name}</strong><p>{m.job_title} · {m.permissions.map(p=>rights.find(x=>x[0]===p)?.[1]).join(', ')}</p><button disabled={busy} className="primary" onClick={()=>run('team-accept',{id:m.id})}>Rejoindre ce cabinet</button></article>)}
 {owner?<><form key={editing?.id||'new'} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(editing?'team-update':'clinic-member-add',{id:editing?.id,email:f.get('email'),job_title:role,permissions,active:editing?f.get('active')==='on':true})}}><h3>{editing?'Modifier les accès de '+editing.name:'Inviter un membre'}</h3><div className="form-grid"><label>E-mail du compte<input name="email" type="email" required defaultValue={editing?.email} disabled={!!editing}/></label><label>Fonction<select value={role} onChange={e=>{setRole(e.target.value);setPermissions(presets[e.target.value])}}>{Object.keys(presets).map(r=><option key={r}>{r}</option>)}</select></label></div><div className="permission-grid">{rights.map(([v,l])=><label className="checkbox" key={v}><input type="checkbox" checked={permissions.includes(v)} onChange={e=>setPermissions(e.target.checked?[...permissions,v]:permissions.filter(x=>x!==v))}/>{l}</label>)}</div>{editing&&<label className="checkbox"><input name="active" type="checkbox" defaultChecked={editing.active}/>Accès actif</label>}<button className="primary" disabled={busy}>{editing?'Enregistrer les droits':'Envoyer l’invitation interne'}</button>{editing&&<button className="secondary" type="button" onClick={()=>setEditing(null)}>Annuler</button>}<p className="muted">Le destinataire accepte l’invitation depuis son espace. Aucun accès clinique n’est accordé par défaut aux assistants.</p></form><div className="member-list">{members.map(m=><article key={m.id}><div><strong>{m.name}</strong><small>{m.job_title} · {m.active?(m.accepted?'Membre actif':'Invitation en attente'):'Accès suspendu'}</small><small>{m.permissions.map(p=>rights.find(x=>x[0]===p)?.[1]).join(' · ')}</small></div><button className="secondary" onClick={()=>{setEditing(m);setRole(m.job_title);setPermissions(m.permissions)}}>Modifier</button></article>)}</div></>:<p>Votre responsable de cabinet gère vos habilitations.</p>}</section>;
}
